version: '3.8'
services:

  kafka:
    image: confluentinc/confluent-local:7.5.1
    container_name: broker
    ports:
      - "9092:9092"
      - "29094:29094"
    environment:
      KAFKA_LISTENERS: LISTENER_INTERNAL://broker:29092,LISTENER_LOCAL://broker:9092,CONTROLLER://localhost:29093,LISTENER_DOCKER://broker:29094
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://broker:29092,LISTENER_LOCAL://localhost:9092,LISTENER_DOCKER://broker:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_LOCAL:PLAINTEXT,CONTROLLER:PLAINTEXT,LISTENER_DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
    volumes:
      - kafka-data:/var/lib/kafka/data
      - kafka-secrets:/etc/kafka/secrets

volumes:
  kafka-data:
    driver: local
  kafka-secrets:
    driver: local